### ISSUE TITLE
Cannot find type 'FrameProcessorPluginBase' in scope

### ISSUE THREAD

**Issue by PiotrKalinski** [yasintorun/vision-camera-base64#1]
Hello,

I am quite newbie in mobile development, I was trying to use your plugin but I got problem with project build

<img width="1519" alt="image" src="https://user-images.githubusercontent.com/19905819/211685206-c95b4ecf-a9c4-442f-9bc8-8befda039cf8.png">

I did pod install, using XCode 14.0.

**Comment by yasintorun** [comment]
If you are building this plugin, please build example/ios project.

**Comment by PiotrKalinski** [comment]
I wanted to build my react-native app to which I added react-native-vision-camera which was working fine but adding plugin crashes build and I am stuck with it. Do I need to do anything else than pod install in /ios folder?

**Comment by yasintorun** [comment]
> I wanted to build my react-native app to which I added react-native-vision-camera which was working fine but adding plugin crashes build and I am stuck with it. Do I need to do anything else than pod install in /ios folder?

No, you don't need anything in the ios folder. The issue seems to be that it doesn't see the vision camera. Is the Vision camera frame processor working?

**Comment by PiotrKalinski** [comment]
Yes but it looks like using yarn it didn't install vision camera for ios, how can I install it manually?

**Comment by yasintorun** [comment]
> Yes but it looks like using yarn it didn't install vision camera for ios, how can I install it manually?

But you said the vision camera is working. Please reinstall `vision camera` and `reanimated` packages.

**Comment by PiotrKalinski** [comment]
Thanks, I manage to pass this issue, now I am having 
`2023-01-12 09:52:54.978909+0100 YuuYoga[3690:1311874] [javascript] TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[9], "vision-camera-base64").frameToBase64')`

my babel.config.js 
`module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    '@fullstory/react-native',
    ['@fullstory/annotate-react', { native: true }],
    [
      'react-native-reanimated/plugin',
      {
        globals: ['__frameToBase64'],
      },
    ],],

  env: {
    production: {
      plugins: [['transform-remove-console', { exclude: ['error', 'warn'] }]]
    }
  }
};`

**Comment by suwu150** [comment]
@PiotrKalinski May I ask how you finally solved this problem?
