### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by PiotrKalinski** [yasintorun/vision-camera-base64#2]
Hello,

I am using your plugin to catch frame and send it back to my server to process image. But after ~15s app crash due to 
<img width="565" alt="image" src="https://user-images.githubusercontent.com/19905819/212055931-db17b042-f1f8-42c1-ba9d-641b5f195594.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/19905819/212055995-eae3dc02-ee79-45ae-977a-5be170da2fb5.png">

is it common issue or am I using it wrong?

**Comment by yasintorun** [comment]
Hi,
I think, `console.log` overflowing memory. 
Please use this code and can you try again?
```javascript
console.log(imageAsBase64.substring(0, 20))
```
or
This code from my real project and this is running correct.
```javascript
const processThread = (base64: string) => {
  // setImage(base64)
  // Get Optic paper with using opencv and c++
  runOpticReader(base64, JSON.stringify(fmt), JSON.stringify(options)).then(setImage);
};
const process = useFrameProcessor((frame) => {
  'worklet';
  // Get QR only qr points
  const detectedBarcodes = scanBarcodes(frame, [BarcodeFormat.QR_CODE], {
    checkInverted: true,
  });
  const points = detectedBarcodes[0]?.cornerPoints;
  if (points && points[1]) {
    fmt.qr = {
      x: points[1].x,
      y: points[1].y,
    };
    const base64 = frameToBase64(frame);
    REA.runOnJS(processThread)(base64);
  }

}, []);
```

**Comment by PiotrKalinski** [comment]
Thanks for help
