### ISSUE TITLE
Cannot find type 'FrameProcessorPluginBase' in scope

### ISSUE THREAD

**Issue by PeterBernanth** [yasintorun/vision-camera-base64#4]
The app was running smoothly with react-native-vision-camera and with frame processor. 
After installing vision-camera-base64 plugin can't able to build the app
<img width="1392" alt="Screenshot 2024-02-01 at 1 06 53 PM" src="https://github.com/yasintorun/vision-camera-base64/assets/106648551/d7b95918-5c5f-4408-826b-2df0996d8e25">

**Comment by thangphamwootech** [comment]
I also is facing with this problem

**Comment by PeterBernanth** [comment]
@thangphamwootech  I think there is no support from this repo for the react-navtive-vision-camera v3 . So I moved to [https://www.npmjs.com/package/vision-camera-base64-v3](url)
